export const ROUTES = {
  // Public
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT: (slug: string) => `/products/${slug}`,
  CATEGORY: (slug: string) => `/categories/${slug}`,
  BRAND: (slug: string) => `/brands/${slug}`,
  FLASH_SALE: "/flash-sale",
  CART: "/cart",
  WISHLIST: "/wishlist",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  CHECKOUT_CANCEL: "/checkout/cancel",
  BLOG: "/blog",
  BLOG_DETAIL: (slug: string) => `/blog/${slug}`,
  ABOUT: "/about",
  CONTACT: "/contact",
  FAQ: "/faq",

  // Auth
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  // User Dashboard
  USER_DASHBOARD: "/dashboard",
  USER_ORDERS: "/user/orders",
  USER_ORDER_DETAIL: (id: string) => `/user/orders/${id}`,
  USER_WISHLIST: "/user/wishlist",
  USER_ADDRESSES: "/user/addresses",
  USER_REVIEWS: "/user/reviews",
  USER_PROFILE: "/user/profile",

  // Seller Dashboard
  SELLER_OVERVIEW: "/seller/overview",
  SELLER_PRODUCTS: "/seller/products",
  SELLER_PRODUCT_CREATE: "/seller/products/create",
  SELLER_PRODUCT_EDIT: (id: string) => `/seller/products/${id}/edit`,
  SELLER_ORDERS: "/seller/orders",
  SELLER_ORDER_DETAIL: (id: string) => `/seller/orders/${id}`,
  SELLER_INVENTORY: "/seller/inventory",
  SELLER_REVIEWS: "/seller/reviews",
  SELLER_PROFILE: "/seller/profile",

  // Admin Dashboard
  ADMIN_OVERVIEW: "/admin/overview",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCT_CREATE: "/admin/products/create",
  ADMIN_PRODUCT_EDIT: (id: string) => `/admin/products/${id}/edit`,
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_BRANDS: "/admin/brands",
  ADMIN_TAGS: "/admin/tags",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_ORDER_DETAIL: (id: string) => `/admin/orders/${id}`,
  ADMIN_USERS: "/admin/users",
  ADMIN_SELLERS: "/admin/sellers",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_COUPONS: "/admin/coupons",
  ADMIN_FLASH_SALES: "/admin/flash-sales",
  ADMIN_BANNERS: "/admin/banners",
  ADMIN_BLOGS: "/admin/blogs",
  ADMIN_BLOG_CREATE: "/admin/blogs/create",
  ADMIN_BLOG_CATEGORIES: "/admin/blog-categories",
  ADMIN_NEWSLETTER: "/admin/newsletter",
  ADMIN_INVENTORY: "/admin/inventory",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_PROFILE: "/admin/profile",
};